### ISSUE TITLE
Insert qoutes after colon

### ISSUE THREAD

**Issue by AgentRBY** [zardoy/vscode-fix-all-json#10]
User has JSON
```json
{
  "someValue": 123,
}
```
He wants to enter a new value, but forgets about the quotes and simply writes:
```json

{
  "someValue": 123,
  newValue:
}
```
I suggest after writing `:` in this case, put quotes automatically: `newValue:` -> `"newValue":`

**Comment by zardoy** [comment]
You can just call Code Actions menu (even assign keybinding to it):
![image](https://user-images.githubusercontent.com/46503702/203663348-4b9338e4-d574-4412-899c-4cc119961aee.png)

Probably you can reuse it when user hits :

**Comment by AgentRBY** [comment]
> Probably you can reuse it when user hits :

I think this is what I will do
I'll look at it tomorrow
