### ISSUE TITLE
Doesn't seem to work on settings.json

### ISSUE THREAD

**Issue by simkimsia** [zardoy/vscode-fix-all-json#20]
this is my settings.json and there are trailing commas
```
{
  "[json]": {
    "editor.defaultFormatter": "zardoy.fix-all-json",
    "editor.codeActionsOnSave": {
      "source.fixAll": true,
    },
  },
  "[python]": {
    "editor.defaultFormatter": "ms-python.black-formatter",
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
      "source.fixAll": true,
    },
  },
  "ruff.args": [
    "--select=E,W,F,I001,PL",
    "--ignore=E203,W503",
    "--per-file-ignores=**/__init__.py:F401"
  ]
}
```

<img width="747" alt="image" src="https://github.com/zardoy/vscode-fix-all-json/assets/245021/6ec35c1b-aa9b-427d-be0f-747a1cfcbbed">

**Comment by zardoy** [comment]
vscode files e.g. settings.json, launch.json, and so on are opened in jsonc format which allows trailing commas. In all .jsonc files trailing commas are reported as warnings (and this extension can catch up these warnings and fix them), but in vscode-specific files vscode defines in schema the fact that it is totally okay to have trailing commas and comments:
https://github.com/microsoft/vscode/blob/c250ed3dcecfbf4f7da851f0373ef0ee4a3b481b/src/vs/workbench/services/configuration/browser/configurationService.ts#L1123

So there is no way to override it even with file associations

**Comment by simkimsia** [comment]
Ok I will close this then

Thanks for answering
