### ISSUE TITLE
Automatically insert a comma on `Enter`

### ISSUE THREAD

**Issue by AgentRBY** [zardoy/vscode-fix-all-json#5]
In WebStorm, if you press `Enter` after curly brackets in JSON, a comma will automatically appear. It would be cool to implement this in VS Code
Example:
![webstorm64_MWRD9ppn9c](https://user-images.githubusercontent.com/68181944/202475931-59da0f79-6241-4484-89e4-6b0a1eee0b3a.gif)

P.S.: Not sure if JSON is specific to this plugin, but either way it would be useful

**Comment by zardoy** [comment]
For now, I personally use [shift+enter keybind](https://github.com/zardoy/vscode-keybindings/blob/071b10892e2d4863d61da0f2afaaf6f69ca4ea8f/package.json#L781), which powered by [Commands](https://marketplace.visualstudio.com/items?itemName=usernamehw.commands) and [Comma Enter](https://marketplace.visualstudio.com/items?itemName=likun.comma-enter) extensions as its useful for absolutely all languages (e.g. objects in TypeScript). In JSON we can easily implement the same behavior as in WS by overriding `Enter` and `Ctrl+Enter`.

> P.S.: Not sure if JSON is specific to this plugin

This extension was originally created to fix errors (diagnostics) in JSON files, but I'm going to add a lot of commands / on-type JSON-specific fixes (such as [autoEscapeQuoteJson](https://github.com/zardoy/vscode-experiments/blob/7e9e428de75290142ba8dc78150da7a507940a29/src/features/autoEscapeJson.ts#L13)) so I think its perfect place for this request.

**Comment by AgentRBY** [comment]
Not a bad solution, but there are problems. Comma Enter generally works everywhere, but in WebStorm the comma only works if the character next to `'` or `"` or `}` or `]`
![webstorm64_gN2eZ2DsZL](https://user-images.githubusercontent.com/68181944/202517990-6aeb5a0c-2f82-43d1-b98a-cc51b6f09d9f.gif)

In VS Code I now have this:
![Code_-_Insiders_31C5qMj90f](https://user-images.githubusercontent.com/68181944/202518108-043336ce-5980-4370-a240-08dc4ab063da.gif)

**Comment by AgentRBY** [comment]
I just tested this on a release extension and it doesn't work for me on two devices. Everything is ok in development mode
@zardoy does this feature work for you?

**Comment by zardoy** [comment]
Yes,

**Comment by zardoy** [comment]
The problem is obvious: it just doesn't work with CRLF, however tests a bit harder to fix than I expected, will do within a few hours.

**Comment by AgentRBY** [comment]
> The problem is obvious: it just doesn't work with CRLF

Oh, okay, I'll fix it after work.

**Comment by zardoy** [comment]
> Oh, okay, I'll fix it after work.

Sorry, didn't see that, the fix was extremely simple, it was initially my failure as I didn't setup tests correctly (file in integration tests was always using LF, dispite of `files.eol` is set to auto)
